### ISSUE TITLE
Change image in comp. sci. queue-insight to accord data structure

### ISSUE THREAD

**Issue by m-lukas** [enkidevs/curriculum#1052]
The data structure of Queues is FIFO like it's also explained in the insight. However, the image explains the model using the terms "Last in"-"First out", which is quite confusing and doesn't accord this model. To fit this insight better for beginners, this should be changed to "First in"-"First out".

**Comment by ryanwarsaw** [comment]
Resolved in #1053, thanks for submitting this issue!
