### ISSUE TITLE
Image Map exercise

### ISSUE THREAD

**Issue by natharas** [enkidevs/curriculum#1328]
Hey it seems the test is broken, tried numerous options but nothing passes. Had a look at the comments in app and appears to have been like this for a week or so.

**Comment by ThomasIAm** [comment]
Any update? The test appears to be updated in the repo but not yet in the app.

**Comment by natharas** [comment]
I don't believe so @ThomasIAm

**Comment by nem035** [comment]
Hey, any chance you can link us to the exact exercise (an insight in this repo) you're referring to?

**Comment by natharas** [comment]
> Hey, any chance you can link us to the exact exercise (an insight in this repo) you're referring to?

Sure can, it's in Web HTML, Advanced Images, Image Map exercise.

**Comment by kapnobatai137** [comment]
The exercise is working correctly now.

![image](https://user-images.githubusercontent.com/19802557/66306946-ed2b0b80-e8fa-11e9-9781-684fe9c90194.png)
