### ISSUE TITLE
Confusing practice question in Python sets topic

### ISSUE THREAD

**Issue by mani2106** [enkidevs/curriculum#1336]
The first revision question in [complex-set-operations](https://github.com/enkidevs/curriculum/blob/master/python/core/more-on-sets/complex-set-operations.md) asks to complete the code snippet such that it will have the desired output (marked in the comment), but there is no comment in the code.

```
python

x = {'user1', 'user2', 'user3'}
y = {'user3'}

x.???(???)
```

I can just add ` # True` to the code so the code snippet can be answered to,  but considering the options.

* issuperset
* y
* x
* issubset

There can be two correct answers 
```
>>> x.issuperset(y)
True

>>> x.issubset(x)
True
```

but only ` x.issuperset(y)` is accepted as the right answer in the lesson.

**Comment by Vedasheersh** [comment]
What you said is absolutely correct as every set is a subset of itself. But since this holds true inspite of what x and y are, it makes sense to go with the first answer.

**Comment by kapnobatai137** [comment]
The issue has now been resolved. Thank you for your contribution, @mani2106 and @Vedasheersh.
