### ISSUE TITLE
Operators II Bug

### ISSUE THREAD

**Issue by lauragirdwood** [enkidevs/curriculum#1388]
At page 5/6 of Operators II a NaN error it is shown via pop-up and the next button redirects to the initial page instead of redirect to a test yourself exercise like usual.

![Screenshot_20190623-225636](https://user-images.githubusercontent.com/8313184/59985896-6a5f9880-960a-11e9-8e5c-c89f09bb90a4.png)

**Comment by lauragirdwood** [comment]
This bug occurs right after click on the Next button at the "varargs" page.

**Comment by lauragirdwood** [comment]
Section Tip I is having the same problem.

![Screenshot_20190623-234412](https://user-images.githubusercontent.com/8313184/59987343-d644ff80-9610-11e9-8530-05fe9dad478d.png)

**Comment by mihaiberq** [comment]
Hey @lauragirdwood , thanks for reporting this issue. I will be looking into the `NaN` bug, but otherwise the app behaves normally: those workouts simply do not have test yourself exercises after every insight.

**Comment by nem035** [comment]
Thanks for the bug report @lauragirdwood 💪

**Comment by nem035** [comment]
This has been fixed
