### ISSUE TITLE
Python - Pretty Print  Data Structures - Suggested Edits

### ISSUE THREAD

**Issue by Areahints** [enkidevs/curriculum#1397]
In the example given for pretty print data structures.

1. It would make sense to make the code beginner friendly, such that

```
data = []
for x in range(4): 
data.append((x,{0:0,1:1})) 
```

2. It would make a lot more sense if you used range(3) instead of range(2) since the square of 0 and 1 are just 0 and 1.

**Comment by kapnobatai137** [comment]
Content has been changed. Thank you for your contribution @Areahints.
