### ISSUE TITLE
Unclear variable declaration in code snippet

### ISSUE THREAD

**Issue by YannikPfeiffer** [enkidevs/curriculum#1404]
File of reference:
Javascript - React - Fundamentals - what is state

In the given code "show" is represented as an attribute of state by calling its value through "this.state.show".
The render method since then was not adjusted so the reference to "show" persists but is never initialized/declared in the constructor.
Instead another attribute replacing show was created named: "text".
So from my perspective this wouldn't compile, or am I missing something?

**Comment by kapnobatai137** [comment]
This has been now fixed, thank you for your input.
