### ISSUE TITLE
No new workouts in the last months and error message

### ISSUE THREAD

**Issue by rciupei** [enkidevs/curriculum#1457]
No new workouts are available. Also the following screen and error message are displayed

![enki](https://user-images.githubusercontent.com/23429709/63049780-2a1de780-bee2-11e9-8304-25c6a2198785.png)

This screen and error are displayed no matter how many times I press "Try to refresh".

I'm using the app since its first days and it worked perfectly until now :smile: 
Thanks in advance!

**Comment by nem035** [comment]
Hi @rciupei thanks for the bug report! Can you provide us with your Enki username so that we can figure out what's going on?

For which topic are you loading the missions here?

**Comment by rciupei** [comment]
Thanks for the quick reply. All the available topics are selected... 
u: raz1234

**Comment by rciupei** [comment]
The issue seem to have been solved (...today I've received new workouts after a few months :) )
Issue can be closed... I'll get in touch with you if the problem reappears.
Thanks a lot!
