### ISSUE TITLE
Incorrect question [Linux - User Perms - Changing File Ownership]

### ISSUE THREAD

**Issue by mickeypash** [enkidevs/curriculum#2164]
While doing the section on User Permissions I noticed that another user had raised a comment saying that [this](https://github.com/enkidevs/curriculum/blob/master/linux/user-and-file-management/user-permissions/changing-file-ownership-with-chown.md#practice) practice question was broken.

The question states that:
```
You can change the owner of a file without having to use sudo when

You have write permissions for the file.
```

A quick check suggests that that might not be the case.

```bash
$ ll
...
-rw-rw-r-- 1 ubuntu ubuntu     7 Jun  3 20:23 words.txt

$ chown jesse words.txt
chown: changing ownership of 'words.txt': Operation not permitted

$ sudo chown jesse ~/words.txt
$ ll
...
-rw-rw-r-- 1 jesse  ubuntu     7 Jun  3 20:23 words.txt
```

If anyone has any suggestions for what question to put instead I'm happy to raise a PR.

**Comment by kapnobatai137** [comment]
Thanks for the report @mickeypash. We'll merge a fix ASAP.

**Comment by kapnobatai137** [comment]
I've update the PQ and did some other improvements (added some resource links and a footnote on `chgrp`).
