### ISSUE TITLE
Python Concurrency

### ISSUE THREAD

**Issue by mickeypash** [enkidevs/curriculum#2177]
Hey team,

I would be interested in contributing to an initial version of Python concurrency workouts. Is that on the roadmap?

**Comment by kapnobatai137** [comment]
Hello @mickeypash 

We think it's great that you want to contribute to our content 💪. Let's start with Python concurrency workouts, and then we can move on to a topic on Redis :smile:.

I want to make this experience as seamless as possible for you, but I will need a bit of time to get everything ready. I'll have everything ready by the end of tomorrow, and will email you with all the details.

**Comment by mickeypash** [comment]
Hey @kapnobatai137,

This makes sense! Thanks for your email! Looking forward to this 👍
