### ISSUE TITLE
Redis workouts

### ISSUE THREAD

**Issue by mickeypash** [enkidevs/curriculum#2178]
Hello, me again, I would also like to work on beginner Redis workouts if that is available?

**Comment by kapnobatai137** [comment]
Hello again @mickeypash :smile:. Let's start off with Python, and then we can move on to Redis. I'll email you all the details soon.

**Comment by hunter1983** [comment]
I just started learning python. I'm would like a career in data science

**Comment by hunter1983** [comment]
I just started learning python. I'm would like a career in data science
