### ISSUE TITLE
Python Issues with Code Examples

### ISSUE THREAD

**Issue by UmbralReaper** [enkidevs/curriculum#2325]
Courses to be changed: 
- Immutability course the lists are named `list`.
- Comprehension, the practice is not fully covered by the example (nor does it accomplish its stated purpose!).
- Algorithms I is cryptic and not entirely accurate

 There are also scattered issues with inappropriately named links.

I’m willing to fix these issues (and any others I come across). This is primarily a placeholder issue.

**Comment by kapnobatai137** [comment]
Hello @UmbralReaper 

Thank you for taking the initiative :muscle: .

If you need any help you can tag me in any issue/pull request, or email me at andrei@enki.com.

Alternatively, you can point out any issue to me and I'll fix it.
