### ISSUE TITLE
Time Zone/New Day

### ISSUE THREAD

**Issue by Normanras** [enkidevs/curriculum#2632]
Hi,

I am in EST time zone and my Enki "days" restart sometime before 1030pm. Which can get a bit frustrating because I sometimes don't have time to do my workout until right before bed and if I miss it I lose my streak. In settings you can select reminder time, but I don't think that's also when the day reset. 

I am happy to contribute a pull request for time zone support, if this is a feature you all think is needed. However, I couldn't find a repo for the app settings. 

Are those settings open for contributions, too?

Thanks again for all your hard work!

**Comment by kapnobatai137** [comment]
Hey Normanras,

Thank you for opening this issue. Unfortunately, that part of the code is not open-source or public, meaning you won't be able to contribute. Thank you for the initiative!

We're working on letting users change their timezone, and we'll implement it in the app soon.

Please check your email when you get the chance. I've included some more information there regarding the streak and changing timezones.

Thank you, and happy learning with Enki 🤓!

**Comment by Normanras** [comment]
Thanks, Andrei! Just replied to your email and will close this out. Keep up the great work!
