### ISSUE TITLE
Wiki clear instructions to define the answers of a question

### ISSUE THREAD

**Issue by saamorim** [enkidevs/curriculum#2751]
The document https://github.com/enkidevs/curriculum/wiki/Insight-Documentation#questions describes how to create questions, but it doesn't cleary explain how to define the right answers. From the examples of the wiki and other questions from the repo, I got it that it is related to the order of the answers.

In the example below:

In order to improve application security, you should periodically ??? your ??? using ???.

- scan <- this is the first answer
- application <- this is the second 
- an automated tool <- third
- attack <- beyond this point are others that are randomly shuffled with the correct ones
- sniff
- crack
- coworker's email
- a password cracker
- a packet sniffer

Taking this in consideration I propose that the after the heading **Questions** and before the subheading **Practice Question** be added an explanation about the format of the content of a question and explain that the order of the answers are relevant.

**Comment by Stefan-Stojanovic** [comment]
Hey @saamorim, thank you for reporting this. I've added a clearer explanation to the wiki along with an example.
