### ISSUE TITLE
DQL typo

### ISSUE THREAD

**Issue by oliviaoddo** [enkidevs/curriculum#472]
File with typo: curriculum/sql/dql/what-is-sql/database-server-types.md
![e2d48cb9-9945-4e76-bd13-bbe4b0c6eb4a](https://user-images.githubusercontent.com/20392250/33365812-4198658c-d49e-11e7-8cad-1142313769bd.jpeg)

**Comment by mihaiberq** [comment]
Fixed. Thanks for reporting!
