### ISSUE TITLE
Revert vs reset typo

### ISSUE THREAD

**Issue by oliviaoddo** [enkidevs/curriculum#473]
File path: curriculum/git/essentials/features-i/reset-vs-revert.md
![0b64a986-a70b-477a-a752-a4d98980f56d](https://user-images.githubusercontent.com/20392250/33366297-ac13fb6e-d49f-11e7-99df-6708e3f6f568.jpeg)

**Comment by mihaiberq** [comment]
Fixed. Thanks for reporting!
