### ISSUE TITLE
Blockchain Fundamentals - Identity and Anonimity

### ISSUE THREAD

**Issue by mihaiberq** [enkidevs/curriculum#557]
The curriculum had undergone some restructuring and the branch insights might not match. If they don't, consider the information here as the source of truth.

Content creation for the [sixth workout](https://github.com/enkidevs/curriculum/tree/blockchain-fundamentals/blockchain/fundamentals/identity-and-anonimity) in the Fundamentals course.

From the list of standards, the ones applicable are:
- Identify blockchain components
- Evaluate potential applications of the blockchain
- Architect a theoretical blockchain

As main points to be covered:
- Identity on the blockchain
- Anonymity and Mixing
- Anonymity on the Bitcoin blockchain

**Comment by ryanwarsaw** [comment]
Appears to be fixed in PR, closing this issue.
