### ISSUE TITLE
Blockchain Fundamentals - Cryptoeconomics

### ISSUE THREAD

**Issue by mihaiberq** [enkidevs/curriculum#561]
The curriculum had undergone some restructuring and the branch insights might not match. If they don't, consider the information here as the source of truth.

Content creation for the [tenth workout](https://github.com/enkidevs/curriculum/tree/blockchain-fundamentals/blockchain/fundamentals/cryptoeconomics) in the Fundamentals course.

From the list of standards, the ones applicable are:
- Identify blockchain components
- Identify differences between cryptocurrencies
- Architect a theoretical blockchain

As main questions to be answered:
- How do cryptocoins acquire exchange value?
- Why is the price fluctuating so much?

**Comment by ryanwarsaw** [comment]
Appears to be fixed in PR, closing this issue.
