### ISSUE TITLE
Blockchain Fundamentals - Ethereum I

### ISSUE THREAD

**Issue by mihaiberq** [enkidevs/curriculum#562]
The curriculum had undergone some restructuring and the branch insights might not match. If they don't, consider the information here as the source of truth.

Content creation for the [eleventh workout](https://github.com/enkidevs/curriculum/tree/blockchain-fundamentals/blockchain/fundamentals/ethereum-i) in the Fundamentals course.

From the [list of standards](https://github.com/sagelabs/standards/pull/38/files), the following should be included in either of the insights:
- bc.analyze-blockchain-components.2
- bc.analyze-blockchain-components.3
- bc.identify-blockchain-applications.3
- bc.identify-blockchain-applications.4
- bc.compare-altcoins.2
- bc.compare-altcoins.5
- bc.analyze-smart-contracts.0

As main questions to be answered:
- What is Ethereum?
- What are smart contracts?
- The account/balance model

**Comment by mihaiberq** [comment]
@EdgarBarrantes will work on this one. (Can't assign you either, will try to figure out why)

**Comment by ryanwarsaw** [comment]
Appears to be fixed in merged PR, closing this issue.
