### ISSUE TITLE
Blockchain Fundamentals - Solidity

### ISSUE THREAD

**Issue by mihaiberq** [enkidevs/curriculum#563]
The curriculum had undergone some restructuring and the branch insights might not match. If they don't, consider the information here as the source of truth.

Content creation for the [twelfth workout](https://github.com/enkidevs/curriculum/tree/blockchain-fundamentals/blockchain/fundamentals/solidity) in the Fundamentals course.

From the list of standards, the ones applicable are:
- Identify blockchain components
- Identify differences between cryptocurrencies
- Architect a theoretical blockchain
- Explain the smart contract inception and fulfillment flow
- Identify security concerns caused by improper configuration or code with Solidity

As main points to be answered:
- What is Solidity?
- Solidity security concerns
- Discuss case studies of heists caused by bugs

**Comment by ryanwarsaw** [comment]
Appears to be fixed in PR, closing this issue.
