### ISSUE TITLE
Blockchain Fundamentals - Ethereum II

### ISSUE THREAD

**Issue by mihaiberq** [enkidevs/curriculum#564]
The curriculum had undergone some restructuring and the branch insights might not match. If they don't, consider the information here as the source of truth.

Content creation for the [thirteenth workout](https://github.com/enkidevs/curriculum/tree/blockchain-fundamentals/blockchain/fundamentals/ethereum-ii) in the Fundamentals course.

From the list of standards, the ones applicable are:
- Identify blockchain components
- Identify differences between cryptocurrencies
- Architect a theoretical blockchain

As main questions to be answered:
- What are ERC20 tokens?
- How do they work?
- What are ICOs?

**Comment by ryanwarsaw** [comment]
Appears to be fixed in PR, closing this issue.
