### ISSUE TITLE
Blockchain Fundamentals - Blockchain on the Web

### ISSUE THREAD

**Issue by mihaiberq** [enkidevs/curriculum#565]
The curriculum had undergone some restructuring and the branch insights might not match. If they don't, consider the information here as the source of truth.

Content creation for the [fourteenth workout](https://github.com/enkidevs/curriculum/tree/blockchain-fundamentals/blockchain/fundamentals/blockchain-on-the-web) in the Fundamentals course.

From the list of standards, the ones applicable are:
- Evaluate potential applications of the blockchain

As main points to be answered:
- MetaMask
- MyEtherWallet

**Comment by ryanwarsaw** [comment]
Appears to be fixed in PR, closing this issue.
