### ISSUE TITLE
[Exercises] JS Standards Exercises

### ISSUE THREAD

**Issue by milesflo** [enkidevs/curriculum#588]
Create branches for each of the following [standards](https://github.com/sagelabs/standards/tree/master/javascript) in `JavaScript`
 - [x] [Identify and Use JavaScript's data types and structures and their respective operations ](https://github.com/enkidevs/curriculum/pull/589)
 - [x] Write Javascript Expressions
 - [x] Evaluate JavaScript Expressions
 - [x] [Use control flow structures to control the flow of a program in JavaScript](https://github.com/enkidevs/curriculum/pull/590)
 - [x] [Use functions in JavaScript](https://github.com/enkidevs/curriculum/pull/591)
 - [x] [Use the standard library to perform common operations on data with JavaScript](https://github.com/enkidevs/curriculum/pull/592)
 - [x] [Perform and manage asynchronous operations in JavaScript](https://github.com/enkidevs/curriculum/pull/597)
 - [x] [Use and manipulate the execution context of a function in JavaScript](https://github.com/enkidevs/curriculum/pull/600)
 - [x] [Use prototypes to create class-like objects in JavaScript](https://github.com/enkidevs/curriculum/pull/611)
 - [x] [Use prototypes to inherit methods and properties from another object in JavaScript](https://github.com/enkidevs/curriculum/pull/611)
 - [x] [Identify and handle exceptions in JavaScript](https://github.com/enkidevs/curriculum/pull/618)

**Comment by lizTheDeveloper** [comment]
- [ ] Change all instances of `Exercises` to `Exercise`
- [ ] Remove exercises from workout files
- [ ] Add exercise file slugs as a list, similar to the `insights` list:
```
insights:
  - insight-slug
  - another-insight-slug

exercises:
  - exercise-slug
  - another-exercise
```

**Comment by lizTheDeveloper** [comment]
these are approved and merged into the `exercises` branch
