### ISSUE TITLE
[Exercises] Python Standards Exercises

### ISSUE THREAD

**Issue by sebaraba** [enkidevs/curriculum#599]
Create `branches` and `PRs` for each standard using codewars.com exercises. This issue covers `Core` standards.

- [x] py.data-structures-uses
- [x] py.store-manipulate-data
- [x] py.native-types-operations
- [x] py.identify-python-syntax
- [x] py.developer-environment
- [x] py.use-iteration-protocol
- [x] py.control-structures
- [x] py.functions
- [x] py.modules
- [x] py.standard-library-operating-system
- [x] py.standard-library-data
- [x] py.object-oriented

**Comment by milesflo** [comment]
@sebaraba Is this issue still open?
