### ISSUE TITLE
JS + Python Exercises Rerendering

### ISSUE THREAD

**Issue by milesflo** [enkidevs/curriculum#641]
These two branches contain Python and JS being rerendered into AST-friendly format

[Python](https://github.com/enkidevs/curriculum/pull/632)
[JavaScript](https://github.com/enkidevs/curriculum/pull/631)

Both branches pass AST-parsing tests, and for good measure I went through and checked every field.

**Comment by lizTheDeveloper** [comment]
@milesflo did you close this with a PR

**Comment by milesflo** [comment]
Both have been merged in. Closing issue.
