### ISSUE TITLE
Make sure all insights with code have lowercase language value

### ISSUE THREAD

**Issue by nem035** [enkidevs/curriculum#647]
For example, some insights have code like this:

```md
```SQL
...
```

When it should be:

```md
```sql
...
```

**Comment by milesflo** [comment]
Seen.

**Comment by Loopiezlol** [comment]
@milesflo can the re-render script deal with this as well?

**Comment by milesflo** [comment]
I could write a regex to look for any string between `\n\`\`\`` and a newline, and replace that toLower

**Comment by Loopiezlol** [comment]
maybe something like  ` ```.*\S\n `
