### ISSUE TITLE
Make this insight more intro-friendly

### ISSUE THREAD

**Issue by lizTheDeveloper** [enkidevs/curriculum#676]
This insight is too deep to introduce the idea of database servers, & it needs a better question. 
It also needs standards.
https://github.com/enkidevs/curriculum/blob/master/sql/dql/what-is-sql/what-is-a-database-server.md

**Comment by claremarie** [comment]
did a rewrite/major paring down on my personal branch: https://github.com/enkidevs/curriculum/blob/clare-sql/sql/dql/what-is-sql/what-is-a-database-server.md
