### ISSUE TITLE
Sort the insights viewed.

### ISSUE THREAD

**Issue by Yatinajmani** [enkidevs/curriculum#786]
Sort the insights according to the contents.

**Comment by lizTheDeveloper** [comment]
Hey @Yatinajmani - could you clarify what you mean by this?

**Comment by Yatinajmani** [comment]
Hey @lizTheDeveloper what this meant was the insights that had been viewed by a person that come under the curriculum part of the app might be in sorted order with respect to content.
For example in this image the insights are not sorted they might be in order
- what is data structure
- what is array
- what is linked list
- what is heap and so on.
![enki](https://user-images.githubusercontent.com/31969705/41116691-a348036e-6aa8-11e8-960d-edccc939fea5.jpg)

**Comment by lizTheDeveloper** [comment]
Thanks for the idea! We're actually working on a new version of the app, which should be out soon! The curriculum page will be reworked, so you'll be able to check out all of the insights in the order they're presented in the app (which has also been reworked 😄)
