### ISSUE TITLE
Slack link doesn't work in readme

### ISSUE THREAD

**Issue by david-kraft** [enkidevs/curriculum#910]
I'd like to join your community. The page I reach when clicking the slack link says:

> This invite link is no longer active.
> If you have an @enki.com email address, you can still create an account.
> 
> If not, please check with the person who shared the invite link with you to ask for an invitation.
>

**Comment by Loopiezlol** [comment]
Hey @david-kraft, thanks for spotting this!

Indeed, the link was not working anymore as we try to get contributors to fill in [this typeform](https://enkidevs.typeform.com/to/bWLaee) before inviting them. Also, feel free to get in contact with us at `content@enki.com` for joining the Slack! 

I have updated the `README.md` to reflect this for the moment.
